### ISSUE TITLE
No JavaScript Stack trace any more ?

### ISSUE THREAD

**Issue by sbougon** [paulirish/automated-chrome-profiling#10]
Hi Paul,

when I use your script (node get-timeline-trace.js) and I open the resulting trace in Chrome (tried M56, M57 and Canary 59), I'm not getting the javaScript stackTrace:
<img width="889" alt="screen shot 2017-03-21 at 9 08 08 pm" src="https://cloud.githubusercontent.com/assets/961999/24181859/0a25720a-0e7b-11e7-874f-a699263d59f2.png">
However, if I profile your website by pressing "record" in the timeline view, I'm getting everything:
<img width="979" alt="screen shot 2017-03-21 at 9 07 45 pm" src="https://cloud.githubusercontent.com/assets/961999/24181867/1d4345e2-0e7b-11e7-8f9d-006ddcf6981c.png">

So, I put a debugger in the devtools code to see what tracing and options were used and got this:
`            "categories":   ["-*", "devtools.timeline", "v8.execute", "disabled-by-default-devtools.timeline", "disabled-by-default-devtools.timeline.frame", "toplevel", "blink.console", "blink.user_timing", "latencyInfo", "disabled-by-default-devtools.timeline.stack"].join(','),
            "options":      "sampling-frequency=10000", 
            "bufferUsageReportingInterval" : 500,
            "transferMode" : "ReportEvents"
`
but, even modifying get-timeline-trace.js with the 4 lines above, I'm still not getting the stack traces.
Do you know what could be the issue ? We are still stuck with the CpuProfile for our automation (via ChromeDriver because of a somewhat related issue), so I wanted to try by hitting Chrome directly, but did not work.

Would appreciate any pointers !

Take care,
Steven
automated-chrome-profiling: latest version
node: v6.2.2
Chrome: 57.0.2987.110 (64-bit)
OS: MacOs 10.12.3

**Comment by paulirish** [comment]
yes. capture these two categories:

> 'disabled-by-default-v8.cpu_profiler',
> 'disabled-by-default-v8.cpu_profiler.hires',

and then in devtools you need to enable the **Timeline tracing based JS profiler** experiment:
![image](https://cloud.githubusercontent.com/assets/39191/24186048/9e9c0a08-0e93-11e7-9e6a-60cb9be19e98.png)

**Comment by sbougon** [comment]
awesome, getting the stack traces now, thanks @paulirish !
<img width="647" alt="screen shot 2017-03-22 at 9 41 02 am" src="https://cloud.githubusercontent.com/assets/961999/24209547/d93b3f4e-0ee3-11e7-8ae8-64eefb7e81df.png">
