### ISSUE TITLE
Jeesus this readme doesn't explain how to Profile another webpage.

### ISSUE THREAD

**Issue by Gerrilicious** [paulirish/automated-chrome-profiling#13]
I am really confused on how to get the profile from for example a localhosted website, help in near feature would be appreciated.

**Comment by paulirish** [comment]
Can you describe what you'd like?

I just updated the js profiler example in 206a651.

take a look: https://github.com/paulirish/automated-chrome-profiling/blob/master/get-cpu-profile.js

**Comment by paulirish** [comment]
mkay
