### ISSUE TITLE
Need help with running automated chrome profile test

### ISSUE THREAD

**Issue by neurites** [paulirish/automated-chrome-profiling#5]
I'm having trouble getting this to run a pilot performance test.

Issue 1 - Instructions in demo/perf-tests.html: "Run the script from this folder: node index.js"
I don't see any index.js in the project so appreciate if you could send in pointers to resolve this. 
We are planning to use this as part of continuous performance testing to get data from chrome profile. 

Issue 2 - Start a server of port 8000 in demo folder. Not able to do that either. 

Appreciate your help!

**Comment by paulirish** [comment]
pushed a commit that makes things simpler. readme should have everything you need now.
